#pragma config(Motor,  port7,           servo,         tmotorServoStandard, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
motor 1 on port8
motor 2 on port9
servo 1 on port7


*/
task main()
{
	/*
	startMotor(port8, -127);
	startMotor(port9, 127);
	wait(30);
	startMotor(port8, 127);
	startMotor(port9, -127);
	wait(30);
	stopMotor(port8);
	stopMotor(port9);
	*/
	setServo(port7, 63);
	setServo(port7, -63);
	setServo(port7, 63);
	setServo(port7, -63);
	setServo(port7, 63);
	setServo(port7, -63);

}
